import React, { useState } from 'react';
import { Entry } from '../../types/entry.types';
import { useApp } from '../../context/AppContext';
import { formatCurrency } from '../../utils/numberFormat';
import { formatDateWithDay } from '../../utils/dateHelpers';
import {
  Activity,
  TrendingUp,
  TrendingDown,
  Percent,
  Calendar,
  Zap,
  Award,
  Copy,
  Check,
  CreditCard,
  Building2,
  Wallet,
  ArrowUpRight,
  ArrowDownRight,
} from 'lucide-react';

interface FinancialHealthCardProps {
  entries: Entry[];
  fromDate: string;
  toDate: string;
  totalIncome: number;
  totalExpense: number;
  netBalance: number;
}

export const FinancialHealthCard: React.FC<FinancialHealthCardProps> = ({
  entries,
  fromDate,
  toDate,
  totalIncome,
  totalExpense,
  netBalance,
}) => {
  const { userProfile } = useApp();
  const [copied, setCopied] = useState<boolean>(false);

  // Calculate day count in date range
  const daysDiff = Math.max(
    1,
    Math.round(
      (new Date(toDate).getTime() - new Date(fromDate).getTime()) / (1000 * 3600 * 24)
    ) + 1
  );

  const avgDailyIncome = Math.round(totalIncome / daysDiff);
  const avgDailyExpense = Math.round(totalExpense / daysDiff);
  const avgDailyNet = Math.round(netBalance / daysDiff);

  // Profit Margin Ratio
  const profitMargin = totalIncome > 0 ? Math.round((netBalance / totalIncome) * 100) : 0;

  // Largest Single Transactions
  let maxIncomeEntry: Entry | null = null;
  let maxExpenseEntry: Entry | null = null;

  entries.forEach((e) => {
    if (e.type === 'income') {
      if (!maxIncomeEntry || e.amount > maxIncomeEntry.amount) {
        maxIncomeEntry = e;
      }
    } else {
      if (!maxExpenseEntry || e.amount > maxExpenseEntry.amount) {
        maxExpenseEntry = e;
      }
    }
  });

  // Payment Mode Detection based on Tags/Categories/Notes
  const paymentModeStats = React.useMemo(() => {
    let cash = 0;
    let bank = 0;
    let digital = 0; // bkash, nagad, online, card

    entries.forEach((e) => {
      const tagsStr = (e.tags || []).join(' ').toLowerCase();
      const descStr = (e.description || '').toLowerCase();
      const combined = `${tagsStr} ${descStr}`;

      if (combined.includes('bank') || combined.includes('cheque') || combined.includes('transfer')) {
        bank += e.amount;
      } else if (
        combined.includes('bkash') ||
        combined.includes('nagad') ||
        combined.includes('online') ||
        combined.includes('card') ||
        combined.includes('upi')
      ) {
        digital += e.amount;
      } else {
        cash += e.amount;
      }
    });

    const totalVal = cash + bank + digital;
    return {
      cash,
      bank,
      digital,
      cashPct: totalVal > 0 ? Math.round((cash / totalVal) * 100) : 100,
      bankPct: totalVal > 0 ? Math.round((bank / totalVal) * 100) : 0,
      digitalPct: totalVal > 0 ? Math.round((digital / totalVal) * 100) : 0,
    };
  }, [entries]);

  // Copy Quick Text Summary to Clipboard
  const handleCopyTextSummary = () => {
    const lang = userProfile.language;
    const currency = userProfile.currency;
    const formattedInc = formatCurrency(totalIncome, lang, currency);
    const formattedExp = formatCurrency(totalExpense, lang, currency);
    const formattedNet = formatCurrency(netBalance, lang, currency);

    const summaryText = `📊 *${userProfile.mainTitle || 'DailyHishab'} Financial Summary*
📅 *Period:* ${fromDate} to ${toDate} (${daysDiff} ${daysDiff === 1 ? 'Day' : 'Days'})

🟢 *Total Income:* ${formattedInc} (${entries.filter((e) => e.type === 'income').length} entries)
🔴 *Total Expense:* ${formattedExp} (${entries.filter((e) => e.type === 'expense').length} entries)
⚖️ *Net Balance:* ${formattedNet}
📈 *Profit Margin:* ${profitMargin}%
⚡ *Avg Daily Cash Flow:* ${formatCurrency(avgDailyNet, lang, currency)}/day

🔗 *App Link:* ${window.location.origin}
_Generated by ${userProfile.mainTitle || 'DailyHishab'}_`;

    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="glass-panel p-5 sm:p-6 space-y-6 rounded-2xl shadow-xl border border-white/50 dark:border-white/10">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 pb-3 border-b border-gray-200/50 dark:border-gray-800">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-indigo-600/10 text-indigo-600 dark:text-indigo-400">
            <Activity className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base sm:text-lg font-bold text-gray-900 dark:text-white">
              Ledger Health & Daily Averages
            </h3>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Key accounting ratios, average daily run-rate, and payment distribution
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={handleCopyTextSummary}
          className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-gray-200/80 dark:bg-gray-800 hover:bg-gray-300 dark:hover:bg-gray-700 text-gray-800 dark:text-gray-200 text-xs font-bold transition-all active:scale-95 cursor-pointer"
          title="Copy fast plain-text summary to clipboard"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5 text-indigo-500" />}
          <span>{copied ? 'Copied to Clipboard!' : 'Copy Quick Summary'}</span>
        </button>
      </div>

      {/* Grid of 4 Key Accounting Ratios */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {/* Profit Margin */}
        <div className="p-3.5 rounded-2xl bg-gradient-to-br from-indigo-500/10 to-blue-500/5 border border-indigo-500/20">
          <div className="flex items-center justify-between mb-1">
            <span className="text-[10px] font-extrabold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">
              Net Profit Margin
            </span>
            <Percent className="w-3.5 h-3.5 text-indigo-500" />
          </div>
          <div className="text-lg sm:text-xl font-black text-gray-900 dark:text-white font-tabular">
            {profitMargin}%
          </div>
          <p className="text-[10px] text-gray-500 dark:text-gray-400 mt-0.5">
            {netBalance >= 0 ? 'Positive retention' : 'Net deficit'}
          </p>
        </div>

        {/* Daily Net Flow */}
        <div className="p-3.5 rounded-2xl bg-gradient-to-br from-blue-500/10 to-teal-500/5 border border-blue-500/20">
          <div className="flex items-center justify-between mb-1">
            <span className="text-[10px] font-extrabold uppercase tracking-wider text-blue-600 dark:text-blue-400">
              Avg Daily Balance
            </span>
            <Zap className="w-3.5 h-3.5 text-blue-500" />
          </div>
          <div className={`text-lg sm:text-xl font-black font-tabular ${avgDailyNet >= 0 ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'}`}>
            {formatCurrency(avgDailyNet, userProfile.language, userProfile.currency)}
          </div>
          <p className="text-[10px] text-gray-500 dark:text-gray-400 mt-0.5">
            Over {daysDiff} {daysDiff === 1 ? 'day' : 'days'}
          </p>
        </div>

        {/* Avg Daily Income */}
        <div className="p-3.5 rounded-2xl bg-gradient-to-br from-emerald-500/10 to-emerald-500/5 border border-emerald-500/20">
          <div className="flex items-center justify-between mb-1">
            <span className="text-[10px] font-extrabold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">
              Avg Daily Revenue
            </span>
            <TrendingUp className="w-3.5 h-3.5 text-emerald-500" />
          </div>
          <div className="text-lg sm:text-xl font-black text-emerald-600 dark:text-emerald-400 font-tabular">
            {formatCurrency(avgDailyIncome, userProfile.language, userProfile.currency)}
          </div>
          <p className="text-[10px] text-gray-500 dark:text-gray-400 mt-0.5">
            Daily cash in
          </p>
        </div>

        {/* Avg Daily Expense */}
        <div className="p-3.5 rounded-2xl bg-gradient-to-br from-rose-500/10 to-rose-500/5 border border-rose-500/20">
          <div className="flex items-center justify-between mb-1">
            <span className="text-[10px] font-extrabold uppercase tracking-wider text-rose-600 dark:text-rose-400">
              Avg Daily Outflow
            </span>
            <TrendingDown className="w-3.5 h-3.5 text-rose-500" />
          </div>
          <div className="text-lg sm:text-xl font-black text-rose-600 dark:text-rose-400 font-tabular">
            {formatCurrency(avgDailyExpense, userProfile.language, userProfile.currency)}
          </div>
          <p className="text-[10px] text-gray-500 dark:text-gray-400 mt-0.5">
            Daily cash out
          </p>
        </div>
      </div>

      {/* Payment Mode Distribution Bar */}
      <div className="p-4 rounded-2xl bg-black/5 dark:bg-white/5 space-y-2 border border-gray-200/50 dark:border-gray-800">
        <div className="flex items-center justify-between text-xs font-bold text-gray-800 dark:text-gray-200">
          <div className="flex items-center gap-1.5">
            <CreditCard className="w-4 h-4 text-purple-500" />
            <span>Payment Mode Breakdown</span>
          </div>
          <div className="flex items-center gap-3 text-[11px]">
            <span className="text-emerald-600 dark:text-emerald-400 font-bold">
              Cash {paymentModeStats.cashPct}%
            </span>
            <span className="text-blue-600 dark:text-blue-400 font-bold">
              Bank {paymentModeStats.bankPct}%
            </span>
            <span className="text-purple-600 dark:text-purple-400 font-bold">
              Digital / Online {paymentModeStats.digitalPct}%
            </span>
          </div>
        </div>

        <div className="w-full h-2.5 bg-gray-200 dark:bg-gray-800 rounded-full overflow-hidden flex">
          <div
            style={{ width: `${paymentModeStats.cashPct}%` }}
            className="h-full bg-emerald-500 transition-all duration-500"
            title={`Cash: ${formatCurrency(paymentModeStats.cash, userProfile.language, userProfile.currency)}`}
          />
          <div
            style={{ width: `${paymentModeStats.bankPct}%` }}
            className="h-full bg-blue-500 transition-all duration-500"
            title={`Bank: ${formatCurrency(paymentModeStats.bank, userProfile.language, userProfile.currency)}`}
          />
          <div
            style={{ width: `${paymentModeStats.digitalPct}%` }}
            className="h-full bg-purple-500 transition-all duration-500"
            title={`Digital: ${formatCurrency(paymentModeStats.digital, userProfile.language, userProfile.currency)}`}
          />
        </div>
      </div>

      {/* Highest Single Transactions Banner */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        {/* Highest Income Entry */}
        <div className="p-3.5 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-between">
          <div className="space-y-0.5">
            <div className="flex items-center gap-1.5 text-[10px] font-extrabold uppercase text-emerald-700 dark:text-emerald-300">
              <Award className="w-3.5 h-3.5" />
              <span>Largest Revenue Record</span>
            </div>
            {maxIncomeEntry ? (
              <>
                <p className="text-xs font-bold text-gray-900 dark:text-white truncate max-w-[200px]">
                  {maxIncomeEntry.description || maxIncomeEntry.category || 'Income Record'}
                </p>
                <span className="text-[10px] text-gray-500">
                  {formatDateWithDay(maxIncomeEntry.date, userProfile.language, true)}
                </span>
              </>
            ) : (
              <p className="text-xs text-gray-400 italic">No income entries in period</p>
            )}
          </div>

          {maxIncomeEntry && (
            <div className="text-right">
              <span className="text-sm sm:text-base font-black text-emerald-600 dark:text-emerald-400 font-tabular">
                +{formatCurrency(maxIncomeEntry.amount, userProfile.language, userProfile.currency)}
              </span>
            </div>
          )}
        </div>

        {/* Highest Expense Entry */}
        <div className="p-3.5 rounded-2xl bg-rose-500/10 border border-rose-500/20 flex items-center justify-between">
          <div className="space-y-0.5">
            <div className="flex items-center gap-1.5 text-[10px] font-extrabold uppercase text-rose-700 dark:text-rose-300">
              <Award className="w-3.5 h-3.5" />
              <span>Largest Single Expense</span>
            </div>
            {maxExpenseEntry ? (
              <>
                <p className="text-xs font-bold text-gray-900 dark:text-white truncate max-w-[200px]">
                  {maxExpenseEntry.description || maxExpenseEntry.category || 'Expense Record'}
                </p>
                <span className="text-[10px] text-gray-500">
                  {formatDateWithDay(maxExpenseEntry.date, userProfile.language, true)}
                </span>
              </>
            ) : (
              <p className="text-xs text-gray-400 italic">No expense entries in period</p>
            )}
          </div>

          {maxExpenseEntry && (
            <div className="text-right">
              <span className="text-sm sm:text-base font-black text-rose-600 dark:text-rose-400 font-tabular">
                -{formatCurrency(maxExpenseEntry.amount, userProfile.language, userProfile.currency)}
              </span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
